### ISSUE TITLE
Crash/Stop on when starting latest version v1.9

### ISSUE THREAD

**Issue by aslmx** [Pygmalion69/OpenTopoMapViewer#10]
Just upgraded to the latest version available on F-Droid and the app immediately crashes or stops when starting. As you are not responsible for the binary shipped via F-Droid i used your "official" build from the release section but it shows the same behaviour.

Does not happen with v1.8.

Device: Samsung SM-G960F
OS: Android 8.1, LineageOS 15.1-20190407-Nightly

Let me know if you need further info:

logcat excerpt:

`01-22 07:29:27.188 D/libgps  ( 4158): GpsiHook: API: gpsSetPositionMode(GpsiHookStateIdle: e,c,g)
01-22 07:29:27.188 D/libgps  ( 4158): proxy__gps_set_position_mode(1, 0, 1000, 0, 0)
01-22 07:29:27.189 D/libgps  ( 4158): GpsiHook: API: gpsStart(GpsiHookStateIdle: e,c,g)
01-22 07:29:27.189 D/libgps  ( 4158): GpsiHookStateIdle             : EXIT
01-22 07:29:27.189 D/libgps  ( 4158): GpsiHookStateGps              : ENTRY
01-22 07:29:27.189 D/libgps  ( 4158): [proxy__gps_start][line = 1164]: called.
01-22 07:29:27.189 D/libgps  ( 4158): GpsiHook: API: gpsStatusCb(GpsiHookStateGps: e,c,g)
01-22 07:29:27.189 D/gpsd    ( 4142): WakeLock(Acquire,GPSD)
01-22 07:29:27.189 D/libgps  ( 4158): GpsiHook: API: gpsStatusCb(GpsiHookStateGps: e,c,g)
01-22 07:29:27.189 I/Sensors ( 4102): batch - accelerometer_sensor try to batching with 50000000
01-22 07:29:27.189 I/GnssLocationProvider( 4338): WakeLock released by handleMessage(SET_REQUEST, 0, com.android.server.location.GnssLocationProvider$GpsRequest@5455ead)
01-22 07:29:27.190 D/gpsd    ( 4142): WakeLock(Release,GPSD)
01-22 07:29:27.190 D/gpsd    ( 4142): WakeLock(Acquire,GPSD)
01-22 07:29:27.190 D/gpsd    ( 4142): WakeLock(Release,GPSD)
01-22 07:29:27.190 D/gpsd    ( 4142): WakeLock(Acquire,GPSD)
01-22 07:29:27.191 D/libgps  ( 4158): OnGpsExtensionMessage: message_id(11), data(0x7a87420044), size(4)
01-22 07:29:27.191 D/libgps  ( 4158): [OnGpsExtensionMessage] Received: MSG_SET_LOG_LEVEL(2)
01-22 07:29:27.191 D/libgps  ( 4158): OnGpsExtensionMessage: message_id(6), data(0x0), size(0)
01-22 07:29:27.191 D/libgps  ( 4158): proxy__gps_xtra_download_request_cb
01-22 07:29:27.192 I/GnssLocationProvider( 4338): WakeLock acquired by sendMessage(DOWNLOAD_XTRA_DATA, 0, null)
01-22 07:29:27.192 I/GnssLocationProvider( 4338): WakeLock acquired by handleDownloadXtraData()
01-22 07:29:27.192 I/GnssLocationProvider( 4338): WakeLock released by handleMessage(DOWNLOAD_XTRA_DATA, 0, null)
01-22 07:29:27.192 E/GpsXtraDownloader( 4338): No XTRA servers were specified in the GPS configuration
01-22 07:29:27.192 I/GnssLocationProvider( 4338): WakeLock acquired by sendMessage(DOWNLOAD_XTRA_DATA_FINISHED, 0, null)
01-22 07:29:27.192 I/GnssLocationProvider( 4338): WakeLock released by handleMessage(DOWNLOAD_XTRA_DATA_FINISHED, 0, null)
01-22 07:29:27.194 I/Sensors ( 4102): batch - geomagnetic_sensor try to batching with 10000000
01-22 07:29:27.194 I/Sensors ( 4102): batch - uncal_gyro_sensor try to batching with 5000000
01-22 07:29:27.194 I/Sensors ( 4102): GeoMagneticSensor old sensor_state 1, new sensor_state : 17 en : 1
01-22 07:29:27.196 I/Sensors ( 4102): UncalGyroSensor old sensor_state 17, new sensor_state : 32785 en : 1
01-22 07:29:27.201 D/AndroidRuntime(32186): Shutting down VM
01-22 07:29:27.201 E/AndroidRuntime(32186): FATAL EXCEPTION: main
01-22 07:29:27.201 E/AndroidRuntime(32186): Process: org.nitri.opentopo, PID: 32186
01-22 07:29:27.201 E/AndroidRuntime(32186): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nitri.opentopo/org.nitri.opentopo.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at android.os.Looper.loop(Looper.java:164)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at java.lang.reflect.Method.invoke(Native Method)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
01-22 07:29:27.201 E/AndroidRuntime(32186): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at org.nitri.opentopo.MapFragment.onViewCreated(MapFragment.java:284)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:298)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1232)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1398)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1476)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1541)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2333)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2120)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2075)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1977)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2862)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2812)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at android.app.Activity.performStart(Activity.java:7029)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
01-22 07:29:27.201 E/AndroidRuntime(32186): 	... 9 more
01-22 07:29:27.204 W/ActivityManager( 4338):   Force finishing activity org.nitri.opentopo/.MainActivity
01-22 07:29:27.206 I/Process (32186): Sending signal. PID: 32186 SIG: 9
01-22 07:29:27.206 D/WifiStateMachine( 4338): fetchRssiLinkSpeedAndFrequencyNative rssi=-62 linkspeed=195 freq=5220
01-22 07:29:27.208 D/WifiScoreReport( 4338):  report new wifi score 60
01-22 07:29:27.339 I/ActivityManager( 4338): Process org.nitri.opentopo (pid 32186) has died: fore TOP 
01-22 07:29:27.339 D/GnssStatusListenerHelper( 4338): Remote Listener died: android.location.IGnssStatusListener$Stub$Proxy@f8b535c
01-22 07:29:27.339 I/Sensors ( 4102): batch - accelerometer_sensor try to batching with 66667000
01-22 07:29:27.340 W/zygote64( 4338): kill(-32186, 9) failed: No such process
01-22 07:29:27.340 I/zygote64( 4338): Successfully killed process cgroup uid 10210 pid 32186 in 0ms
01-22 07:29:27.344 I/Sensors ( 4102): GeoMagneticSensor old sensor_state 32785, new sensor_state : 32769 en : 0
01-22 07:29:27.352 I/Sensors ( 4102): UncalGyroSensor old sensor_state 32769, new sensor_state : 1 en : 0
01-22 07:29:27.354 D/WindowManager( 4338): relayoutVisibleWindow: Window{9d59ba4 u0 org.lineageos.trebuchet/com.android.launcher3.searchlauncher.SearchLauncher EXITING} mAnimatingExit=true, mRemoveOnExit=false, mDestroying=false
01-22 07:29:27.372 D/mali_winsys( 5127): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
01-22 07:29:27.421 I/GnssLocationProvider( 4338): WakeLock acquired by sendMessage(SET_REQUEST, 0, com.android.server.location.GnssLocationProvider$GpsRequest@e78d7c7)`

**Comment by Pygmalion69** [comment]
Thank you. This should be fixed in the next release.
