### ISSUE TITLE
Feature request: remember last location after closure and user defined setting of map files dir

### ISSUE THREAD

**Issue by achmed-hub** [Pygmalion69/OpenTopoMapViewer#11]
Thank you very much for your most useful app.

normally i am with gps disabled on android (for good reasons). 
when it comes to planing tours or downloading maps you always have to scroll from the start in central atlantic (west of africa) to your specific location in interest. Why not simply remember the last location and start topomaps the next time at this point, if gps is off? Small change with huge benefit for many users, i presume.
another extremly fine feature would be user-defined setting of maps directory (external SD card for instance)

with best regards
Dr. Achim Wentzel

**Comment by Pygmalion69** [comment]
Thank you for your suggestions. The map center should be persisted after the last modifications. Also, I've added some cache settings.

![cache_settings](https://user-images.githubusercontent.com/6958566/76095447-966a5080-5fc4-11ea-8430-c78cb7f7ce5f.png)

**Comment by achmed-hub** [comment]
thank you a lot,

map center saving works fine. Changing max cache size has no effect (on android 9): on reaching about 600Mb the db is shrinked to about 500-550 Mb regardless of the setting.
The ability to also change storage root (SD card!) would be appreciated.
