### ISSUE TITLE
Crash on GPX file opening

### ISSUE THREAD

**Issue by Poussinou** [Pygmalion69/OpenTopoMapViewer#2]
Hi,

Well everything is in the title. I'm trying to load a gpx file produced by another android app downloaded via F-Droid named [GPSLogger](https://apt.izzysoft.de/fdroid/index/apk/com.mendhak.gpslogger).

After picking the file, the app simply crash.

Ask me if you have any question regarding this bug ;)

**Comment by Pygmalion69** [comment]
Joda-Time was missing from the build, so time tags could not be parsed.

**Comment by Poussinou** [comment]
Thanks, I'll peek the update via F-Droid ASAP 👍

**Comment by Poussinou** [comment]
Everything works fine now, thanks a lot 👍
