### ISSUE TITLE
no / very slow map loading

### ISSUE THREAD

**Issue by linesquarecube** [Pygmalion69/OpenTopoMapViewer#25]
Sometimes the map is not loading at all or just very very slow - e. g.  2-3 minutes for the currently displayed map section. The issue appears to concern both OpenTopoMap as well as OpenStreeMap. Sometimes the map is not displayed at all or a previously correct displayed map section is gone after zooming in/out.

The overlays for Lonvia Hiking or Lonvia Cycling are shown without any problem.

I've attached a screenshot which shows a section after around 2 minutes of loading.
<img src="https://user-images.githubusercontent.com/81855936/216078203-7d6184d6-8792-41d5-b561-c77b0b57ab95.png" width=50% height=50%>

I've already tried deleting cache and reinstalling the app.

Thanks for your help :smiley:

**Comment by Pygmalion69** [comment]
This fully depends on your connection speed and the performance of the tile servers at opentopomap.org and openstreetmap.org. The app does not affect this.

We consider implementing tile pre-loading at some point in the future.
