### ISSUE TITLE
"Walk" through GPX path

### ISSUE THREAD

**Issue by bovergaauw** [Pygmalion69/OpenTopoMapViewer#29]
Would it be possible to "walk" through a GPX path to see from which point to which next point someone went? I'm using GPXLogger to track my movements and would like to replay them. I couldn't find any app that could do this. In case I wasn't clear, please contact me.

**Comment by Pygmalion69** [comment]
This app does not offer that functionality. I use [GPX Player](https://gpxplayer.nitri.org/) to replay GPX tracks but I'm not sure if that suits your use case as it runs off-device.
