### ISSUE TITLE
RFE: provide open street map as well

### ISSUE THREAD

**Issue by herrdeh** [Pygmalion69/OpenTopoMapViewer#3]
Thank you for this app and all the effort you put into it.
I'd like very much to have an option to choose vanilla OpenStreetMaps to be displayed. Topographic maps are very good in the country side, but maybe not first choice if you're moving in a city.

I'm using the app as a very quickly launching alternative to fat navigators - when I get out of the underground and have to find my last few meters to my destination. But on TopoMaps, you need to zoom in to the last two zoom levels to see all street names and house numbers

I used this one before [LocationMapViewer](https://f-droid.org/de/packages/de.k3b.android.locationMapViewer/), but it does not center automatically to my location and does not have the "follow" feature, both of them are definitive "must-haves".

**Comment by Pygmalion69** [comment]
Thank you for your feedback. This has been implemented in release 1.4.

**Comment by herrdeh** [comment]
GREEEEAAAAATTTTTTT !!!

Don't know how other people are dealing with that issue - but to me this is one of THE killer features of a smartphone - and your app is the first I found which really solves that issue. You made my day!

I passed by Ede-Wageningen station several times years ago when I had to do with a really crazy lady from Driebergen...
