### ISSUE TITLE
Initial position by opening app

### ISSUE THREAD

**Issue by tiffiw** [Pygmalion69/OpenTopoMapViewer#6]
It is somehow very confusing to see at the beginning always a blue screen indicating the coordinates 0/0 somewhere in the Atlantic near Africa. Wouldn't it be better to show the last position used until the GPS signal is found?
This is by the way also the case when you rotate the device.

**Comment by Pygmalion69** [comment]
It now uses the last known location on app start and saved state on orientation change (release 1.7).
